export const ENTERAS = '/'
export const LOGIN = '/login'
export const MYPRODUCTS = '/myproducts'
export const CONFIGURATION_REQUESTS = '/configurationrequests'
export const BUY = '/buy'
export const PRODUCTS = '/products'
export const REGISTERPRODUCT = '/registerproduct'
